### ISSUE TITLE
Create enum for socket events

### ISSUE THREAD

**Issue by fhaynes** [LucioFranco/amethyst-protocol#10]
# Problem
We need a set of events that we can pass up to the application.

# Solution
Probably an enum? 

## Events
At a minimum, we need:

1. Client Connected
2. Client Disconnected (only for TCP clients)
3. Client Timed Out
3. Client Reconnected (this one is a maybe, see below)
4. Client Connection Quality Changed

### Reconnected Event
The only way we have of identifying a remote user at layer 3 is via the remote IP and remote port. There are cases where these may change, but it is the same client. We'll see this frequently when people are behind NAT, for example.

If we do get a reconnection from the same ip:port combo, we can either treat that as a reconnection and assume it is the same remote client, or we treat it as a brand new connection. 

Ultimately, the application will need to embed a unique identifier for their clients in the payload part of the packets.

**Comment by LucioFranco** [comment]
@fhaynes I believe there should also be a `MessageRecieved` event so that the user of the library has one place to handle ALL events that come through the socket.
