### ISSUE TITLE
Come up with a proper name and move to the amethyst org

### ISSUE THREAD

**Issue by LucioFranco** [LucioFranco/amethyst-protocol#23]
We need to come up with a new name for this repo/crate.

My initial thought was `Aquamarine` which is another gem similar to `Amethyst`.
https://en.wikipedia.org/wiki/Beryl#Aquamarine_and_maxixe

I would like to hear more thoughts.

**Comment by Moxinilian** [comment]
My suggestion would be `laminar`.

This adjective is both used in geology, describing __mineral crystals__ that look like flat planes, and in thermodynamics where it describes a flow that is not turbulent, streamlined and fast. I think it fits perfectly the idea one would want to carry with the protocol. It also is available on crates.io

> adjective
> 1. consisting of laminae.
> "The lowest part consists of the mineral neomesselite, which has a delicate laminar or platelike structure."
> 2. (of a flow) taking place along constant streamlines; not turbulent.
> "Since air in laminar flow has a higher pressure than turbulent air, the laminar flow behind the ball creates less of a ‘sucking’ effect behind the ball which would substantially slow it down."

**Comment by LucioFranco** [comment]
This has been done. Please checkout https://github.com/amethyst/laminar
